
package com.accenture.flowershop.be.business;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FlowerStockWebServiceImplService", targetNamespace = "http://business.be.flowershop.accenture.com/", wsdlLocation = "http://localhost:8080/flowershop/ws/flowers?wsdl")
public class FlowerStockWebServiceImplService
    extends Service
{

    private final static URL FLOWERSTOCKWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FLOWERSTOCKWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName FLOWERSTOCKWEBSERVICEIMPLSERVICE_QNAME = new QName("http://business.be.flowershop.accenture.com/", "FlowerStockWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/flowershop/ws/flowers?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLOWERSTOCKWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        FLOWERSTOCKWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public FlowerStockWebServiceImplService() {
        super(__getWsdlLocation(), FLOWERSTOCKWEBSERVICEIMPLSERVICE_QNAME);
    }

    public FlowerStockWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLOWERSTOCKWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public FlowerStockWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, FLOWERSTOCKWEBSERVICEIMPLSERVICE_QNAME);
    }

    public FlowerStockWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLOWERSTOCKWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public FlowerStockWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlowerStockWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlowerStockWebService
     */
    @WebEndpoint(name = "FlowerStockWebServiceImplPort")
    public FlowerStockWebService getFlowerStockWebServiceImplPort() {
        return super.getPort(new QName("http://business.be.flowershop.accenture.com/", "FlowerStockWebServiceImplPort"), FlowerStockWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlowerStockWebService
     */
    @WebEndpoint(name = "FlowerStockWebServiceImplPort")
    public FlowerStockWebService getFlowerStockWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://business.be.flowershop.accenture.com/", "FlowerStockWebServiceImplPort"), FlowerStockWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLOWERSTOCKWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw FLOWERSTOCKWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return FLOWERSTOCKWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
